# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # - repo: local
  #   hooks:
  #     - id: poetry-pytest
  #       name: Run pytest with Poetry
  #       entry: poetry run --directory backend pytest
  #       language: system
  #       pass_filenames: false
  #       always_run: true
  #       files: ^backend/
  #     # - id: poetry-pyright
  #     #   name: Run pyright with Poetry
  #     #   entry: poetry run --directory backend pyright
  #     #   language: system
  #     #   pass_filenames: false
  #     #   always_run: true
  #     #   files: ^backend/
